[versions]
agp = "8.11.1"

android-jvm = "17"
android-compileSdk = "35"
android-targetSdk = "35"
android-minSdk = "21"

[plugins]
# Android Gradle Plugin
agp-lib = { id = "com.android.library", version.ref = "agp" }
agp-app = { id = "com.android.application", version.ref = "agp" } 
